'use strict'

const { Genre } = require('../../src/models')

exports.seed = (knex, Promise) => knex(Genre.tableName).del()
  .then(() => [
    { name: 'Action' },
    { name: 'Platform games' },
    { name: 'Shooter games' },
    { name: 'Fighting games' },
    { name: 'Beat \'em up games' },
    { name: 'Stealth game' },
    { name: 'Survival games' },
    { name: 'Rhythm games' },
    { name: 'Action-adventure' },
    { name: 'Survival horror' },
    { name: 'Metroidvania' },
    { name: 'Adventure' },
    { name: 'Text adventures' },
    { name: 'Graphic adventures' },
    { name: 'Visual novels' },
    { name: 'Interactive movie' },
    { name: 'Real-time 3D adventures' },
    { name: 'Role-playing' },
    { name: 'Action RPG' },
    { name: 'MMORPG' },
    { name: 'Roguelikes' },
    { name: 'Tactical RPG' },
    { name: 'Sandbox RPG' },
    { name: 'First-person party-based RPG' },
    { name: 'Cultural differences' },
    { name: 'Choices' },
    { name: 'Fantasy' },
    { name: 'Simulation' },
    { name: 'Construction and management simulation' },
    { name: 'Life simulation' },
    { name: 'Vehicle simulation' },
    { name: 'Strategy' },
    { name: '4X game' },
    { name: 'Artillery game' },
    { name: 'Real-time strategy (RTS)' },
    { name: 'Real-time tactics (RTT)' },
    { name: 'Multiplayer online battle arena (MOBA)' },
    { name: 'Tower defense' },
    { name: 'Turn-based strategy (TBS)' },
    { name: 'Turn-based tactics (TBT)' },
    { name: 'Wargame' },
    { name: 'Grand strategy wargame' },
    { name: 'Sports' },
    { name: 'Racing' },
    { name: 'Sports game' },
    { name: 'Competitive' },
    { name: 'Sports-based fighting' },
    { name: 'Other notable genres' },
    { name: 'MMO' },
    { name: 'Casual games' },
    { name: 'Party game' },
    { name: 'Programming game' },
    { name: 'Logic game' },
    { name: 'Trivia game' },
    { name: 'Board game / Card game' },
    { name: 'Idle gaming' },
    { name: 'Video game genres by purpose' },
    { name: 'Advergame' },
    { name: 'Art game' },
    { name: 'Casual game' },
    { name: 'Christian game' },
    { name: 'Educational game' },
    { name: 'Electronic sports' },
    { name: 'Exergame' },
    { name: 'Personalized game' },
    { name: 'Serious game' },
    { name: 'Scientific studies' },
    { name: 'See also' },
    { name: 'Game interfaces' },
    { name: 'Game platforms' },
    { name: 'Other related topics' },
    { name: 'Notes' },
    { name: 'References' },
    { name: 'Bibliography' }
  ])
  .then(newGenres => Promise.all(newGenres.map(genre => Genre.create(genre))))
  .catch(err => console.log('err: ', err))