'use strict'

const { Company } = require('../../src/models')

exports.seed = (knex, Promise) => knex(Company.tableName).del()
  .then(() => [
    
    // Publisher
    { name: '07th Expansion', publisher: true },
    { name: '1C Company', publisher: true },
    { name: '2K Games', publisher: true },
    { name: '3D Realms', publisher: true },
    { name: 'The 3DO Company', publisher: true },
    { name: 'The Fourth Dimension', publisher: true },
    { name: '505 Games', publisher: true },
    { name: '5pb.', publisher: true },
    { name: '7th Level', publisher: true },
    { name: 'A&F Software', publisher: true },
    { name: 'Aackosoft', publisher: true },
    { name: 'Aardvark Software', publisher: true },
    { name: 'ABC Software', publisher: true },
    { name: 'Absolute Entertainment', publisher: true },
    { name: 'Access Software', publisher: true },
    { name: 'Accolade', publisher: true },
    { name: 'Acquire', publisher: true },
    { name: 'Acornsoft', publisher: true },
    { name: 'Acclaim Entertainment', publisher: true },
    { name: 'Active Gaming Media AGM', publisher: true },
    { name: 'Addictive Games', publisher: true },
    { name: 'The Adventure Company', publisher: true },
    { name: 'Adventure International', publisher: true },
    { name: 'Activision', publisher: true },
    { name: 'Activision Blizzard', publisher: true },
    { name: 'Adventure Soft', publisher: true },
    { name: 'Affect', publisher: true },
    { name: 'Agatsuma Entertainment', publisher: true },
    { name: 'Âge', publisher: true },
    { name: 'AGEod', publisher: true },
    { name: 'Agetec', publisher: true },
    { name: 'Akabeisoft2', publisher: true },
    { name: 'Akella', publisher: true },
    { name: 'Akupara Games', publisher: true },
    { name: 'Aksys', publisher: true },
    { name: 'ALcot', publisher: true },
    { name: 'AliceSoft', publisher: true },
    { name: 'AlphaDream', publisher: true },
    { name: 'ADK', publisher: true },
    { name: 'Alchemist', publisher: true },
    { name: 'Allumer', publisher: true },
    { name: 'Alten8', publisher: true },
    { name: 'Alternative Software', publisher: true },
    { name: 'American Game Cartridges', publisher: true },
    { name: 'American Laser Games', publisher: true },
    { name: 'American Video Entertainment', publisher: true },
    { name: 'Amplitude Studios', publisher: true },
    { name: 'Amsoft', publisher: true },
    { name: 'ANALOG Software', publisher: true },
    { name: 'Andamiro', publisher: true },
    { name: 'Antic Software', publisher: true },
    { name: 'Anuman', publisher: true },
    { name: 'APF Electronics Inc.', publisher: true },
    { name: 'Apogee Software', publisher: true },
    { name: 'Apple Inc.', publisher: true },
    { name: 'Aquaplus', publisher: true },
    { name: 'AQ Interactive', publisher: true },
    { name: 'Arcadia Systems', publisher: true },
    { name: 'Arc System Works', publisher: true },
    { name: 'Argus Press', publisher: true },
    { name: 'Arika', publisher: true },
    { name: 'Ariolasoft', publisher: true },
    { name: 'Armor Games', publisher: true },
    { name: 'Arsys Software', publisher: true },
    { name: 'Artdink', publisher: true },
    { name: 'Artic Computing', publisher: true },
    { name: 'Arush Entertainment', publisher: true },
    { name: 'Arxel Tribe', publisher: true },
    { name: 'Ascaron', publisher: true },
    { name: 'ASC Games', publisher: true },
    { name: 'Asmik Corporation of America', publisher: true },
    { name: 'Aspyr Media', publisher: true },
    { name: 'Astragon', publisher: true },
    { name: 'Atari, Inc', publisher: true },
    { name: 'Atari, SA', publisher: true },
    { name: 'Athena', publisher: true },
    { name: 'Atlantis Software', publisher: true },
    { name: 'AQ Interactive', publisher: true },
    { name: 'Artech Digital Entertainment', publisher: true },
    { name: 'ASCII Corporation', publisher: true },
    { name: 'Atlus', publisher: true },
    { name: 'Attic Entertainment Software', publisher: true },
    { name: 'Audiogenic Limited', publisher: true },
    { name: 'August', publisher: true },
    { name: 'Auran Development', publisher: true },
    { name: 'Automata UK', publisher: true },
    { name: 'Autumn Games', publisher: true },
    { name: 'Avalon Hill', publisher: true },
    { name: 'Aventuras AD', publisher: true },
    { name: 'Aventurine SA', publisher: true },
    { name: 'BAM! Entertainment', publisher: true },
    { name: 'Bandai Games', publisher: true },
    { name: 'Bandai Namco Entertainment', publisher: true },
    { name: 'Banpresto', publisher: true },
    { name: 'BBC Multimedia', publisher: true },
    { name: 'Beagle Bros', publisher: true },
    { name: 'Bergsala Lightweight', publisher: true },
    { name: 'Berkeley Systems', publisher: true },
    { name: 'Bethesda Softworks', publisher: true },
    { name: 'Beyond Software', publisher: true },
    { name: 'Big Fish Games', publisher: true },
    { name: 'Big Five Software', publisher: true },
    { name: 'Bigben Interactive', publisher: true },
    { name: 'Alligata', publisher: true },
    { name: 'Black Bean Games', publisher: true },
    { name: 'Blue Byte', publisher: true },
    { name: 'Broderbund', publisher: true },
    { name: 'Black Legend', publisher: true },
    { name: 'Blizzard Entertainment', publisher: true },
    { name: 'Blue Ribbon', publisher: true },
    { name: 'Bohemia Interactive', publisher: true },
    { name: 'Box Office, Inc.', publisher: true },
    { name: 'Brash Entertainment', publisher: true },
    { name: 'Broccoli', publisher: true },
    { name: 'Bug-Byte', publisher: true },
    { name: 'Bubble Bus Software', publisher: true },
    { name: 'BudgeCo', publisher: true },
    { name: 'Buka Entertainment', publisher: true },
    { name: 'Bullet-Proof Software', publisher: true },
    { name: 'Bungie', publisher: true },
    { name: 'C&E', publisher: true },
    { name: 'California Dreams', publisher: true },
    { name: 'California Pacific Computer Company', publisher: true },
    { name: 'Camerica', publisher: true },
    { name: 'Canal+ Multimedia', publisher: true },
    { name: 'Candy Soft', publisher: true },
    { name: 'Capcom', publisher: true },
    { name: 'Capstone Software', publisher: true },
    { name: 'Caramel Box', publisher: true },
    { name: 'Carry Lab', publisher: true },
    { name: 'Casady & Greene', publisher: true },
    { name: 'Cases Computer Simulations', publisher: true },
    { name: 'Cave', publisher: true },
    { name: 'CBS Electronics', publisher: true },
    { name: 'CD Projekt Red', publisher: true },
    { name: 'CDS Software', publisher: true },
    { name: 'CDV Software Entertainment AG', publisher: true },
    { name: 'Centuri', publisher: true },
    { name: 'CE Software', publisher: true },
    { name: 'ChessBase', publisher: true },
    { name: 'Chunsoft', publisher: true },
    { name: 'Cinemax', publisher: true },
    { name: 'CI Games', publisher: true },
    { name: 'Cinematronics', publisher: true },
    { name: 'Cinemaware', publisher: true },
    { name: 'Circus', publisher: true },
    { name: 'Club Kidsoft', publisher: true },
    { name: 'The Coca-Cola Company', publisher: true },
    { name: 'Codemasters', publisher: true },
    { name: 'Coktel Vision', publisher: true },
    { name: 'Coleco', publisher: true },
    { name: 'Color Dreams', publisher: true },
    { name: 'CommaVid', publisher: true },
    { name: 'Commercial Data Systems', publisher: true },
    { name: 'Commodore', publisher: true },
    { name: 'Compile', publisher: true },
    { name: 'Compile Heart', publisher: true },
    { name: 'Computer and Video Games', publisher: true },
    { name: 'Conspiracy Entertainment', publisher: true },
    { name: 'Core Design', publisher: true },
    { name: 'Cosmi Corporation', publisher: true },
    { name: 'Crave Entertainment', publisher: true },
    { name: 'Creative Computing', publisher: true },
    { name: 'Creatures', publisher: true },
    { name: 'Crimson Cow', publisher: true },
    { name: 'CRL Group', publisher: true },
    { name: 'Cronosoft', publisher: true },
    { name: 'Culture Brain', publisher: true },
    { name: 'Cryo Interactive', publisher: true },
    { name: 'Crystal Computing', publisher: true },
    { name: 'Crystal Dynamics', publisher: true },
    { name: 'Crytek', publisher: true },
    { name: 'Cyberdreams', publisher: true },
    { name: 'Cyberdreams', publisher: true },
    { name: 'Cybersoft', publisher: true },
    { name: 'D3 Publisher', publisher: true },
    { name: 'Daedalic Entertainment', publisher: true },
    { name: 'DarXabre', publisher: true },
    { name: 'Datamost', publisher: true },
    { name: 'Datam Polystar', publisher: true },
    { name: 'Datasoft', publisher: true },
    { name: 'Data Age', publisher: true },
    { name: 'Data Becker', publisher: true },
    { name: 'Data Design Interactive', publisher: true },
    { name: 'Davidson & Associates', publisher: true },
    { name: 'Davilex Games', publisher: true },
    { name: 'Davka', publisher: true },
    { name: 'Daybreak Game Company', publisher: true },
    { name: 'Data East', publisher: true },
    { name: 'dB-SOFT', publisher: true },
    { name: 'Deep Silver', publisher: true },
    { name: 'Delphine Software International', publisher: true },
    { name: 'Delta 4', publisher: true },
    { name: 'Destination Software', publisher: true },
    { name: 'Destineer', publisher: true },
    { name: 'Devolver Digital', publisher: true },
    { name: 'Digital Fantasia', publisher: true },
    { name: 'Digital Integration', publisher: true },
    { name: 'Digital Jesters', publisher: true },
    { name: 'Digital Leisure', publisher: true },
    { name: 'Digital Pictures', publisher: true },
    { name: 'Dinamic Multimedia', publisher: true },
    { name: 'Dinamic Software', publisher: true },
    { name: 'Disney Interactive Studios', publisher: true },
    { name: 'DK\'Tronics', publisher: true },
    { name: 'Domark', publisher: true },
    { name: 'Dovetail Games', publisher: true },
    { name: 'Draconus Entertainment', publisher: true },
    { name: 'Dragon Data', publisher: true },
    { name: 'DreamCatcher Games', publisher: true },
    { name: 'DreamWorks Interactive', publisher: true },
    { name: 'DROsoft', publisher: true },
    { name: 'Dtp entertainment', publisher: true },
    { name: 'Dynamix', publisher: true },
    { name: 'EasyGameStation', publisher: true },
    { name: 'Ecole Software', publisher: true },
    { name: 'Edu-Ware', publisher: true },
    { name: 'eGames', publisher: true },
    { name: 'Electric Dreams Software', publisher: true },
    { name: 'Electronic Arts', publisher: true },
    { name: 'Electronic Arts Victor', publisher: true },
    { name: 'Electro Brain', publisher: true },
    { name: 'The Elektrik Keyboard', publisher: true },
    { name: 'ELF Corporation', publisher: true },
    { name: 'Elite Systems', publisher: true },
    { name: 'Empire Interactive', publisher: true },
    { name: 'English Software', publisher: true },
    { name: 'Enix', publisher: true },
    { name: 'Enlight Software', publisher: true },
    { name: 'Enterbrain', publisher: true },
    { name: 'Durell Software', publisher: true },
    { name: 'Edge Games', publisher: true },
    { name: 'Eighting', publisher: true },
    { name: 'Electric Transit', publisher: true },
    { name: 'Emerald Software', publisher: true },
    { name: 'Encore, Inc.', publisher: true },
    { name: 'Entertainment Software Publishing', publisher: true },
    { name: 'En Masse Entertainment', publisher: true },
    { name: 'Eolith', publisher: true },
    { name: 'Eon Digital Entertainment', publisher: true },
    { name: 'Epic Games', publisher: true },
    { name: 'Epoch Co.', publisher: true },
    { name: 'Epyx', publisher: true },
    { name: 'ERE Informatique', publisher: true },
    { name: 'Europress', publisher: true },
    { name: 'Eushully', publisher: true },
    { name: 'Examu', publisher: true },
    { name: 'Excalibur Publishing', publisher: true },
    { name: 'Exidy', publisher: true },
    { name: 'F&C', publisher: true },
    { name: 'FASA', publisher: true },
    { name: 'Fabtek', publisher: true },
    { name: 'Fairchild Semiconductor', publisher: true },
    { name: 'Family Soft', publisher: true },
    { name: 'Fantasy Software', publisher: true },
    { name: 'Faster Than Light', publisher: true },
    { name: 'Fathammer', publisher: true },
    { name: 'Firebird Software', publisher: true },
    { name: 'First Star Software', publisher: true },
    { name: 'Feral Interactive', publisher: true },
    { name: 'Fill-in-Cafe', publisher: true },
    { name: 'Fisher Price', publisher: true },
    { name: 'Fishtank Interactive', publisher: true },
    { name: 'Flair Software', publisher: true },
    { name: 'Flight-Plan', publisher: true },
    { name: 'Flying Edge', publisher: true },
    { name: 'Focus Home Interactive', publisher: true },
    { name: 'Focus Multimedia', publisher: true },
    { name: 'FormGen', publisher: true },
    { name: 'Fox Interactive', publisher: true },
    { name: 'Freeverse Software', publisher: true },
    { name: 'French Bread', publisher: true },
    { name: 'Fresh Games', publisher: true },
    { name: 'Froggo', publisher: true },
    { name: 'FromSoftware', publisher: true },
    { name: 'Front Wing', publisher: true },
    { name: 'FTL Games', publisher: true },
    { name: 'Fujisankei Communications International', publisher: true },
    { name: 'Fujitsu', publisher: true },
    { name: 'Full On Games', publisher: true },
    { name: 'Funcom', publisher: true },
    { name: 'Future Games', publisher: true },
    { name: 'Fuuki', publisher: true },
    { name: 'G-Collections', publisher: true },
    { name: 'G.rev', publisher: true },
    { name: 'Gaelco', publisher: true },
    { name: 'Gaijinworks', publisher: true },
    { name: 'Gainax', publisher: true },
    { name: 'Gakken', publisher: true },
    { name: 'Gamecock', publisher: true },
    { name: 'Gameloft', publisher: true },
    { name: 'Games by Apollo', publisher: true },
    { name: 'Games Workshop', publisher: true },
    { name: 'GAMÉRICA', publisher: true },
    { name: 'GameTek', publisher: true },
    { name: 'Game Arts', publisher: true },
    { name: 'The Game Factory', publisher: true },
    { name: 'Game Park', publisher: true },
    { name: 'Game Studio', publisher: true },
    { name: 'Gargoyle Games', publisher: true },
    { name: 'Gathering of Developers', publisher: true },
    { name: 'Gearbox Software', publisher: true },
    { name: 'General Entertainment', publisher: true },
    { name: 'Genki', publisher: true },
    { name: 'Ghostlight', publisher: true },
    { name: 'Global Star Software', publisher: true },
    { name: 'Gathering of Developers', publisher: true },
    { name: 'Gebelli Software', publisher: true },
    { name: 'Giga', publisher: true },
    { name: 'Gizmondo', publisher: true },
    { name: 'Global A Entertainment', publisher: true },
    { name: 'Global VR', publisher: true },
    { name: 'GN Software', publisher: true },
    { name: 'GOG Ltd', publisher: true },
    { name: 'Gogii Games', publisher: true },
    { name: 'Gotham Games', publisher: true },
    { name: 'Gottlieb', publisher: true },
    { name: 'Got Game Entertainment', publisher: true },
    { name: 'Grandslam Entertainment', publisher: true },
    { name: 'Graphsim Entertainment', publisher: true },
    { name: 'Gravity', publisher: true },
    { name: 'Great Wave Software', publisher: true },
    { name: 'Gremlin Industries', publisher: true },
    { name: 'Gremlin Interactive', publisher: true },
    { name: 'Grolier Interactive Inc', publisher: true },
    { name: 'Groove Games', publisher: true },
    { name: 'GSC World Publishing', publisher: true },
    { name: 'GTE Interactive Media', publisher: true },
    { name: 'GT Interactive', publisher: true },
    { name: 'GungHo Online Entertainment', publisher: true },
    { name: 'Gust Corporation', publisher: true },
    { name: 'Hacker International', publisher: true },
    { name: 'Haikuo Soft', publisher: true },
    { name: 'HAL Laboratory', publisher: true },
    { name: 'Hamster Corporation', publisher: true },
    { name: 'HanbitSoft', publisher: true },
    { name: 'Hasbro Interactive', publisher: true },
    { name: 'Hect', publisher: true },
    { name: 'Her Interactive', publisher: true },
    { name: 'Heureka-Klett', publisher: true },
    { name: 'Hi Tech Expressions', publisher: true },
    { name: 'Hewson Consultants', publisher: true },
    { name: 'Hirameki', publisher: true },
    { name: 'Hodder & Stoughton', publisher: true },
    { name: 'Home Entertainment Suppliers', publisher: true },
    { name: 'Hooksoft', publisher: true },
    { name: 'HopeLab', publisher: true },
    { name: 'Houghton Mifflin Harcourt', publisher: true },
    { name: 'Hudson Soft', publisher: true },
    { name: 'Human Engineered Software', publisher: true },
    { name: 'Human Entertainment', publisher: true },
    { name: 'HummingBirdSoft', publisher: true },
    { name: 'Humongous Entertainment', publisher: true },
    { name: 'IBM', publisher: true },
    { name: 'Iceberg Interactive', publisher: true },
    { name: 'ICOM Simulations', publisher: true },
    { name: 'Idea Factory', publisher: true },
    { name: 'id Software', publisher: true },
    { name: 'Ignition Entertainment', publisher: true },
    { name: 'Illusion Soft', publisher: true },
    { name: 'Imageepoch', publisher: true },
    { name: 'Image Works', publisher: true },
    { name: 'Imagic', publisher: true },
    { name: 'Imagine Software', publisher: true },
    { name: 'Impressions Games', publisher: true },
    { name: 'Incentive Software', publisher: true },
    { name: 'Incredible Technologies', publisher: true },
    { name: 'index+', publisher: true },
    { name: 'IndieBox', publisher: true },
    { name: 'indiePub Entertainment', publisher: true },
    { name: 'Infocom', publisher: true },
    { name: 'Infogrames', publisher: true },
    { name: 'Innerprise Software', publisher: true },
    { name: 'Inscape', publisher: true },
    { name: 'Intellivision Productions', publisher: true },
    { name: 'Interactive Magic', publisher: true },
    { name: 'Interceptor Micros', publisher: true },
    { name: 'Interchannel', publisher: true },
    { name: 'International Games System', publisher: true },
    { name: 'Interplay Entertainment', publisher: true },
    { name: 'Introversion Software', publisher: true },
    { name: 'INTV Corporation', publisher: true },
    { name: 'inXile Entertainment', publisher: true },
    { name: 'iQue', publisher: true },
    { name: 'Irem', publisher: true },
    { name: 'ITE Media', publisher: true },
    { name: 'J.K. Greye Software', publisher: true },
    { name: 'Jaleco', publisher: true },
    { name: 'JAST USA', publisher: true },
    { name: 'Jester Interactive', publisher: true },
    { name: 'Johnson & Johnson', publisher: true },
    { name: 'JoWooD Productions', publisher: true },
    { name: 'K2 Network (Gamersfirst)', publisher: true },
    { name: 'Kalisto Entertainment', publisher: true },
    { name: 'Kalypso Media', publisher: true },
    { name: 'Kaneko', publisher: true },
    { name: 'Kaypro', publisher: true },
    { name: 'Kemco', publisher: true },
    { name: 'King Games', publisher: true },
    { name: 'KID', publisher: true },
    { name: 'Kingsoft', publisher: true },
    { name: 'King Records', publisher: true },
    { name: 'Knowledge Adventure', publisher: true },
    { name: 'Koch Media', publisher: true },
    { name: 'Koei', publisher: true },
    { name: 'Koei Tecmo', publisher: true },
    { name: 'Kogado Studio', publisher: true },
    { name: 'Konami', publisher: true },
    { name: 'Krisalis Software', publisher: true },
    { name: 'KSS', publisher: true },
    { name: 'Kure Software Koubou', publisher: true },
    { name: 'La\'cryma', publisher: true },
    { name: 'Lankhor', publisher: true },
    { name: 'Le Lombard', publisher: true },
    { name: 'Legacy Interactive', publisher: true },
    { name: 'Legendo', publisher: true },
    { name: 'Legend Entertainment', publisher: true },
    { name: 'Lego Interactive', publisher: true },
    { name: 'Leland Corporation', publisher: true },
    { name: 'Level-5', publisher: true },
    { name: 'Level 9 Computing', publisher: true },
    { name: 'Limited Run Games', publisher: true },
    { name: 'Linux Game Publishing', publisher: true },
    { name: 'Lighthouse Interactive', publisher: true },
    { name: 'LJN', publisher: true },
    { name: 'LK Avalon', publisher: true },
    { name: 'Llamasoft', publisher: true },
    { name: 'Logotron Ltd', publisher: true },
    { name: 'Loki Software', publisher: true },
    { name: 'Loriciel', publisher: true },
    { name: 'LucasArts', publisher: true },
    { name: 'Lump of Sugar', publisher: true },
    { name: 'MacPlay', publisher: true },
    { name: 'MacSoft', publisher: true },
    { name: 'Mad Catz', publisher: true },
    { name: 'Magical Company', publisher: true },
    { name: 'Magnavox', publisher: true },
    { name: 'Mr Chip Software', publisher: true },
    { name: 'magnussoft', publisher: true },
    { name: 'Mandarin Software', publisher: true },
    { name: 'MangaGamer', publisher: true },
    { name: 'Martech', publisher: true },
    { name: 'Majesco Entertainment', publisher: true },
    { name: 'Marvelous AQL', publisher: true },
    { name: 'Marvelous Entertainment', publisher: true },
    { name: 'Masaya', publisher: true },
    { name: 'Mastertronic', publisher: true },
    { name: 'Mastiff', publisher: true },
    { name: 'Matrix Games', publisher: true },
    { name: 'Mattel', publisher: true },
    { name: 'Maximum Games', publisher: true },
    { name: 'Maxis', publisher: true },
    { name: 'Max Design', publisher: true },
    { name: 'MC2 France', publisher: true },
    { name: 'MC Lothlorien', publisher: true },
    { name: 'MECC', publisher: true },
    { name: 'MediaWorks', publisher: true },
    { name: 'Media Factory', publisher: true },
    { name: 'Media Rings', publisher: true },
    { name: 'Mega Enterprise', publisher: true },
    { name: 'Melbourne House', publisher: true },
    { name: 'Meldac', publisher: true },
    { name: 'Metro3D, Inc.', publisher: true },
    { name: 'Metropolis Software', publisher: true },
    { name: 'MGM Interactive', publisher: true },
    { name: 'Microdeal', publisher: true },
    { name: 'Microïds', publisher: true },
    { name: 'MicroIllusions', publisher: true },
    { name: 'Micronet co., Ltd.', publisher: true },
    { name: 'MicroProse', publisher: true },
    { name: 'Microsoft', publisher: true },
    { name: 'Microsphere', publisher: true },
    { name: 'Microcabin', publisher: true },
    { name: 'Micrografx', publisher: true },
    { name: 'MicroGraphic Image', publisher: true },
    { name: 'Micro Genius', publisher: true },
    { name: 'Micro Power', publisher: true },
    { name: 'Midas Interactive Entertainment', publisher: true },
    { name: 'Midway Games', publisher: true },
    { name: 'Midway Manufacturing', publisher: true },
    { name: 'Mikro-Gen', publisher: true },
    { name: 'MileStone Inc.', publisher: true },
    { name: 'Millennium Interactive', publisher: true },
    { name: 'Milton Bradley Company', publisher: true },
    { name: 'Minato Soft', publisher: true },
    { name: 'Mindscape', publisher: true },
    { name: 'Mindcraft', publisher: true },
    { name: 'Minori', publisher: true },
    { name: 'Mirrorsoft', publisher: true },
    { name: 'Mitchell Corporation', publisher: true },
    { name: 'Mojang', publisher: true },
    { name: 'Monolith Productions', publisher: true },
    { name: 'Monte Cristo', publisher: true },
    { name: 'Moonstone', publisher: true },
    { name: 'Mosaic Publishing', publisher: true },
    { name: 'MOSS', publisher: true },
    { name: 'Motown Games', publisher: true },
    { name: 'Mountain King Studios', publisher: true },
    { name: 'MTO', publisher: true },
    { name: 'MTV Games', publisher: true },
    { name: 'Mud Duck Productions', publisher: true },
    { name: 'Muse Software', publisher: true },
    { name: 'MumboJumbo', publisher: true },
    { name: 'Mystique', publisher: true },
    { name: 'Namco', publisher: true },
    { name: 'Natsume Co Ltd', publisher: true },
    { name: 'Natsume Inc', publisher: true },
    { name: 'Navel', publisher: true },
    { name: 'Naxat Soft', publisher: true },
    { name: 'NCsoft', publisher: true },
    { name: 'NEC Corporation', publisher: true },
    { name: 'Neko Entertainment', publisher: true },
    { name: 'Netdragon', publisher: true },
    { name: 'Netease', publisher: true },
    { name: 'New Generation Software', publisher: true },
    { name: 'NewKidCo', publisher: true },
    { name: 'New World Computing', publisher: true },
    { name: 'Nexon', publisher: true },
    { name: 'Nihon Falcom', publisher: true },
    { name: 'Nintendo', publisher: true },
    { name: 'Nippon Ichi Software', publisher: true },
    { name: 'Nihon Bussan', publisher: true },
    { name: 'Nitroplus', publisher: true },
    { name: 'Novagen Software', publisher: true },
    { name: 'Nokia', publisher: true },
    { name: 'Nordcurrent', publisher: true },
    { name: 'NovaLogic', publisher: true },
    { name: 'Nova Games', publisher: true },
    { name: 'NTDEC', publisher: true },
    { name: 'Nutting Associates', publisher: true },
    { name: 'O3 Entertainment', publisher: true },
    { name: 'Ocean Software', publisher: true },
    { name: 'Ocean State Publishing', publisher: true },
    { name: 'Odin Computer Graphics', publisher: true },
    { name: 'Opera Soft', publisher: true },
    { name: 'Orbital Media', publisher: true },
    { name: 'Origin Systems', publisher: true },
    { name: 'Orion Interactive', publisher: true },
    { name: 'Out of the Park Developments', publisher: true },
    { name: '0verflow', publisher: true },
    { name: 'Oxygen Games', publisher: true },
    { name: 'OziSoft', publisher: true },
    { name: 'Pacific Novelty', publisher: true },
    { name: 'Pack-In-Video', publisher: true },
    { name: 'Palace Software', publisher: true },
    { name: 'Palette', publisher: true },
    { name: 'Panda Entertainment', publisher: true },
    { name: 'Panasonic', publisher: true },
    { name: 'Panesian Taiwan', publisher: true },
    { name: 'Panther Games', publisher: true },
    { name: 'Panther Software', publisher: true },
    { name: 'Paradox Interactive', publisher: true },
    { name: 'Paragon Software', publisher: true },
    { name: 'Parker Brothers', publisher: true },
    { name: 'Parsoft Interactive', publisher: true },
    { name: 'Peach Princess', publisher: true },
    { name: 'Penguin Software', publisher: true },
    { name: 'Pentavision', publisher: true },
    { name: 'Perfect World', publisher: true },
    { name: 'Personal Software Services', publisher: true },
    { name: 'Petit Ferret', publisher: true },
    { name: 'Petroglyph Games', publisher: true },
    { name: 'PF Magic', publisher: true },
    { name: 'Phantagram', publisher: true },
    { name: 'Philips', publisher: true },
    { name: 'Pionesoft', publisher: true },
    { name: 'Piranha Games', publisher: true },
    { name: 'Piranha Interactive Publishing', publisher: true },
    { name: 'PlayFirst', publisher: true },
    { name: 'Playlogic Entertainment, Inc.', publisher: true },
    { name: 'Playmates Toys', publisher: true },
    { name: 'The Pokémon Company', publisher: true },
    { name: 'Pony Canyon', publisher: true },
    { name: 'PopCap Games', publisher: true },
    { name: 'Positech Games', publisher: true },
    { name: 'Presto Studios', publisher: true },
    { name: 'PrincessSoft', publisher: true },
    { name: 'Prism Leisure Corporation', publisher: true },
    { name: 'Probe Software', publisher: true },
    { name: 'Programma International', publisher: true },
    { name: 'Prolific Publishing', publisher: true },
    { name: 'Prototype', publisher: true },
    { name: 'Psygnosis', publisher: true },
    { name: 'Psikyo', publisher: true },
    { name: 'Psycho', publisher: true },
    { name: 'Psytronik Software', publisher: true },
    { name: 'Pulltop', publisher: true },
    { name: 'Purple Moon', publisher: true },
    { name: 'Purple software', publisher: true },
    { name: 'Quality Software', publisher: true },
    { name: 'Quantum Axcess', publisher: true },
    { name: 'Quantum Quality Productions', publisher: true },
    { name: 'Quest Corporation', publisher: true },
    { name: 'Quicksilva', publisher: true },
    { name: 'QuinRose', publisher: true },
    { name: 'Quintet', publisher: true },
    { name: 'Qute', publisher: true },
    { name: 'Q Entertainment', publisher: true },
    { name: 'R&P Electronic Media', publisher: true },
    { name: 'R2Games', publisher: true },
    { name: 'Rabbit Software', publisher: true },
    { name: 'Radica Games', publisher: true },
    { name: 'Rage Software', publisher: true },
    { name: 'Rainbird Software', publisher: true },
    { name: 'Rainbow Arts', publisher: true },
    { name: 'Rare', publisher: true },
    { name: 'Raster_Entertainment', publisher: true },
    { name: 'Ravensburger Interactive', publisher: true },
    { name: 'Raw Thrills', publisher: true },
    { name: 'Red Ant Enterprises', publisher: true },
    { name: 'Red Barrels', publisher: true },
    { name: 'Red Entertainment', publisher: true },
    { name: 'RedOctane', publisher: true },
    { name: 'Red Orb Entertainment', publisher: true },
    { name: 'Red Shift', publisher: true },
    { name: 'RedSpotGames', publisher: true },
    { name: 'Red Storm Entertainment', publisher: true },
    { name: 'Regista', publisher: true },
    { name: 'reLINE Software', publisher: true },
    { name: 'Renegade Software', publisher: true },
    { name: 'Renovation Products', publisher: true },
    { name: 'Richard Shepherd Software', publisher: true },
    { name: 'Right Stuff', publisher: true },
    { name: 'Riot Games', publisher: true },
    { name: 'Ripcord Games', publisher: true },
    { name: 'Rising Star Games', publisher: true },
    { name: 'Riverhillsoft', publisher: true },
    { name: 'Rock-Ola', publisher: true },
    { name: 'Rockstar Games', publisher: true },
    { name: 'Romstar', publisher: true },
    { name: 'Romtech', publisher: true },
    { name: 'Rovio Entertainment', publisher: true },
    { name: 'RTL Group', publisher: true },
    { name: 'RuneSoft', publisher: true },
    { name: 'Saga Planets', publisher: true },
    { name: 'Sanctuary Woods', publisher: true },
    { name: 'Scavenger, Inc.', publisher: true },
    { name: 'Sammy Studios', publisher: true },
    { name: 'SCi Games', publisher: true },
    { name: 'Safari Software', publisher: true },
    { name: 'Scholastic', publisher: true },
    { name: 'Sears', publisher: true },
    { name: 'Sega', publisher: true },
    { name: 'Seibu Kaihatsu', publisher: true },
    { name: 'SETA Corporation', publisher: true },
    { name: 'Shadow Tor Studios', publisher: true },
    { name: 'Shanda', publisher: true },
    { name: 'Sharp Corporation', publisher: true },
    { name: 'Sherston Software', publisher: true },
    { name: 'Dynamic Planning', publisher: true },
    { name: 'Shoeisha', publisher: true },
    { name: 'Shogakukan', publisher: true },
    { name: 'Shrapnel Games', publisher: true },
    { name: 'Sierra Entertainment', publisher: true },
    { name: 'Silicon Beach Software', publisher: true },
    { name: 'Silmarils', publisher: true },
    { name: 'Simon & Schuster Interactive', publisher: true },
    { name: 'SIMS Co., Ltd.', publisher: true },
    { name: 'Simulations Canada', publisher: true },
    { name: 'Sinclair Research Ltd.', publisher: true },
    { name: 'Sirius Software', publisher: true },
    { name: 'Sir-Tech', publisher: true },
    { name: 'Slitherine', publisher: true },
    { name: 'SNK', publisher: true },
    { name: 'Soedesco', publisher: true },
    { name: 'SOFEL', publisher: true },
    { name: 'Soft-World', publisher: true },
    { name: 'Softape', publisher: true },
    { name: 'Softdisk', publisher: true },
    { name: 'SoftKey', publisher: true },
    { name: 'Softek International Ltd', publisher: true },
    { name: 'Softmax', publisher: true },
    { name: 'SoftSide', publisher: true },
    { name: 'Softstar', publisher: true },
    { name: 'Software 2000', publisher: true },
    { name: 'Software Dynamics', publisher: true },
    { name: 'Software Projects', publisher: true },
    { name: 'Sony Imagesoft', publisher: true },
    { name: 'Sony Interactive Entertainment', publisher: true },
    { name: 'Sony Pictures Digital', publisher: true },
    { name: 'SouthPeak Games', publisher: true },
    { name: 'Spectral Associates', publisher: true },
    { name: 'Spectravideo', publisher: true },
    { name: 'Spectrum HoloByte', publisher: true },
    { name: 'Spike', publisher: true },
    { name: 'Spil Games', publisher: true },
    { name: 'Spinnaker Software', publisher: true },
    { name: 'Square', publisher: true },
    { name: 'Square Electronic Arts', publisher: true },
    { name: 'Square Enix', publisher: true },
    { name: 'Square Enix Europe', publisher: true },
    { name: 'Stardock', publisher: true },
    { name: 'Starpath', publisher: true },
    { name: 'Stern Electronics', publisher: true },
    { name: 'Sting Entertainment', publisher: true },
    { name: 'Storm Impact', publisher: true },
    { name: 'Strategic Simulations (SSI)', publisher: true },
    { name: 'Strategic Studies Group', publisher: true },
    { name: 'Stormfront Studios', publisher: true },
    { name: 'Strategy First', publisher: true },
    { name: 'Studio e.go!', publisher: true },
    { name: 'subLOGIC', publisher: true },
    { name: 'Success', publisher: true },
    { name: 'Sunflowers Interactive Entertainment Software', publisher: true },
    { name: 'Sunrise Interactive', publisher: true },
    { name: 'Sunsoft', publisher: true },
    { name: 'Superior Software', publisher: true },
    { name: 'Supersoft', publisher: true },
    { name: 'Sydney Development Corporation', publisher: true },
    { name: 'Super Fighter Team', publisher: true },
    { name: 'Suzy Soft', publisher: true },
    { name: 'Synapse Software', publisher: true },
    { name: 'Synergistic Software', publisher: true },
    { name: 'SystemSoft', publisher: true },
    { name: 'System 3', publisher: true },
    { name: 'System Sacom', publisher: true },
    { name: 'Tactics', publisher: true },
    { name: 'Taito', publisher: true },
    { name: 'Takara', publisher: true },
    { name: 'Takara Tomy', publisher: true },
    { name: 'Take-Two Interactive', publisher: true },
    { name: 'TalonSoft', publisher: true },
    { name: 'Tamsoft', publisher: true },
    { name: 'Tandy Corporation', publisher: true },
    { name: 'Taxan', publisher: true },
    { name: 'TDK Mediactive', publisher: true },
    { name: 'Team17', publisher: true },
    { name: 'Team Shanghai Alice', publisher: true },
    { name: 'Techland', publisher: true },
    { name: 'Technology and Entertainment Software', publisher: true },
    { name: 'Technosoft', publisher: true },
    { name: 'Technos Japan', publisher: true },
    { name: 'TecMagik', publisher: true },
    { name: 'Tecmo', publisher: true },
    { name: 'Tectoy', publisher: true },
    { name: 'Telarium', publisher: true },
    { name: 'Telesys', publisher: true },
    { name: 'Telenet Japan', publisher: true },
    { name: 'Telltale Games', publisher: true },
    { name: 'Tencent', publisher: true },
    { name: 'Tengen', publisher: true },
    { name: 'Texas Instruments', publisher: true },
    { name: 'Technical Group Laboratory', publisher: true },
    { name: 'Thalamus Ltd', publisher: true },
    { name: 'Thalion Software', publisher: true },
    { name: 'The9', publisher: true },
    { name: 'The Learning Company', publisher: true },
    { name: 'Thin Chen Enterprise', publisher: true },
    { name: 'Thinking Rabbit', publisher: true },
    { name: 'THQ', publisher: true },
    { name: 'THQ Nordic', publisher: true },
    { name: 'Thorn EMI Computer Software', publisher: true },
    { name: 'Three-Sixty Pacific', publisher: true },
    { name: 'Tiertex Design Studios', publisher: true },
    { name: 'Tiger Electronics', publisher: true },
    { name: 'Time Warner Interactive', publisher: true },
    { name: 'Titus Interactive', publisher: true },
    { name: 'Toaplan', publisher: true },
    { name: 'Toei Animation', publisher: true },
    { name: 'Toho', publisher: true },
    { name: 'Tokuma Shoten', publisher: true },
    { name: 'Tokyo Shoseki', publisher: true },
    { name: 'Tomy', publisher: true },
    { name: 'Tonkin House', publisher: true },
    { name: 'Topologika', publisher: true },
    { name: 'Topo Soft', publisher: true },
    { name: 'TopWare Interactive', publisher: true },
    { name: 'Toshiba EMI', publisher: true },
    { name: 'Towa Chiki', publisher: true },
    { name: 'Tradewest', publisher: true },
    { name: 'Treco', publisher: true },
    { name: 'Triangle Service', publisher: true },
    { name: 'Triffix Entertainment', publisher: true },
    { name: 'Trilobyte Software', publisher: true },
    { name: 'Tripwire Interactive', publisher: true },
    { name: 'Tri Synergy', publisher: true },
    { name: 'Tru Blu Entertainment', publisher: true },
    { name: 'Tsunami Games', publisher: true },
    { name: 'TT Games', publisher: true },
    { name: 'Twilight Frontier', publisher: true },
    { name: 'Tynesoft', publisher: true },
    { name: 'Type-Moon', publisher: true },
    { name: 'Ubisoft', publisher: true },
    { name: 'UEP Systems', publisher: true },
    { name: 'UFO Interactive Games', publisher: true },
    { name: 'Ultimate Play the Game', publisher: true },
    { name: 'Ultrasoft', publisher: true },
    { name: 'Ultra Games', publisher: true },
    { name: 'United States Army', publisher: true },
    { name: 'Universal Entertainment Corporation', publisher: true },
    { name: 'U.S. Gold', publisher: true },
    { name: 'UserJoy Technology', publisher: true },
    { name: 'US Games', publisher: true },
    { name: 'Valcon Games', publisher: true },
    { name: 'Valve Corporation', publisher: true },
    { name: 'VAP', publisher: true },
    { name: 'Varie', publisher: true },
    { name: 'VEB Polytechnik', publisher: true },
    { name: 'Vectorbeam', publisher: true },
    { name: 'Viacom', publisher: true },
    { name: 'Victor Interactive', publisher: true },
    { name: 'Vic Tokai', publisher: true },
    { name: 'Video System', publisher: true },
    { name: 'Virgin Interactive', publisher: true },
    { name: 'Virgin Play', publisher: true },
    { name: 'Virtual Programming', publisher: true },
    { name: 'Visco Corporation', publisher: true },
    { name: 'The Vision Factory', publisher: true },
    { name: 'VisualArt\'s', publisher: true },
    { name: 'OPeNBooK Co., Ltd.', publisher: true },
    { name: 'Viva Media', publisher: true },
    { name: 'Vivendi Games', publisher: true },
    { name: 'Vortex Software', publisher: true },
    { name: 'VoxelStorm', publisher: true },
    { name: 'Vulcan Software', publisher: true },
    { name: 'Wales Interactive', publisher: true },
    { name: 'Walnut Creek CDROM', publisher: true },
    { name: 'Wanadoo Edition', publisher: true },
    { name: 'Warashi', publisher: true },
    { name: 'Wargaming.net', publisher: true },
    { name: 'Warner Bros. Interactive', publisher: true },
    { name: 'WARP', publisher: true },
    { name: 'Webfoot Technologies', publisher: true },
    { name: 'Webzen', publisher: true },
    { name: 'WildTangent', publisher: true },
    { name: 'Williams Electronics', publisher: true },
    { name: 'Windham Classics', publisher: true },
    { name: 'Windmill', publisher: true },
    { name: 'Windmill Software', publisher: true },
    { name: 'Winkysoft', publisher: true },
    { name: 'Wisdom Tree', publisher: true },
    { name: 'WizardWorks', publisher: true },
    { name: 'Wolf Team', publisher: true },
    { name: 'Working Designs', publisher: true },
    { name: 'Xicat Interactive', publisher: true },
    { name: 'Xonox', publisher: true },
    { name: 'XSEED Games', publisher: true },
    { name: 'XS Games', publisher: true },
    { name: 'Yeti', publisher: true },
    { name: 'Yuisy', publisher: true },
    { name: 'Yojigen', publisher: true },
    { name: 'Yonezawa PR21', publisher: true },
    { name: 'Yuke\'s', publisher: true },
    { name: 'Yutaka', publisher: true },
    { name: 'Zaccaria', publisher: true },
    { name: 'ZAPiT Games', publisher: true },
    { name: 'ZeniMax Media', publisher: true },
    { name: 'Zenobi', publisher: true },
    { name: 'Zeppelin Games', publisher: true },
    { name: 'Zigurat', publisher: true },
    { name: 'Zimag', publisher: true },
    { name: 'Zoom', publisher: true },
    { name: 'Zuxxez Entertainment', publisher: true },
    { name: 'Zushi Games', publisher: true },
    { name: 'Zynga', publisher: true },
    { name: 'ZyX', publisher: true },
    
    // Developer
    { name: '0verflow', developer: true },
    { name: '11 bit studios', developer: true },
    { name: '1st Playable Productions', developer: true },
    { name: '1-UP Studio', developer: true },
    { name: '2K Czech', developer: true },
    { name: '2K Games', developer: true },
    { name: '2K Sports', developer: true },
    { name: '2XL Games', developer: true },
    { name: '343 Industries', developer: true },
    { name: '38 Studios', developer: true },
    { name: '3D Realms', developer: true },
    { name: '3G Studios', developer: true },
    { name: '42 Entertainment', developer: true },
    { name: '4A Games', developer: true },
    { name: '5th Cell', developer: true },
    { name: '989 Studios', developer: true },
    { name: 'Acclaim Entertainment', developer: true },
    { name: 'Accolade', developer: true },
    { name: 'Access Games', developer: true },
    { name: 'Access Software', developer: true },
    { name: 'ACE Team', developer: true },
    { name: 'Aces Studio', developer: true },
    { name: 'Acheron Design', developer: true },
    { name: 'Action Forms', developer: true },
    { name: 'Active Gaming Media', developer: true },
    { name: 'Activision', developer: true },
    { name: 'Adventure Soft', developer: true },
    { name: 'Akella', developer: true },
    { name: 'Alfa System', developer: true },
    { name: 'Amazon Game Studios', developer: true },
    { name: 'Ancient', developer: true },
    { name: 'Anino', developer: true },
    { name: 'Ankama Games', developer: true },
    { name: 'Appy Entertainment', developer: true },
    { name: 'AQ Interactive', developer: true },
    { name: 'Arc System Works', developer: true },
    { name: 'Arcane Kids', developer: true },
    { name: 'Arkane Studios', developer: true },
    { name: 'Arkedo Studio', developer: true },
    { name: 'ArenaNet', developer: true },
    { name: 'Arika', developer: true },
    { name: 'Art Co., Ltd', developer: true },
    { name: 'Artdink', developer: true },
    { name: 'ArtePiazza', developer: true },
    { name: 'Artificial Studios', developer: true },
    { name: 'Artoon', developer: true },
    { name: 'Arzest', developer: true },
    { name: 'Ascaron', developer: true },
    { name: 'Asobo Studio', developer: true },
    { name: 'Atari, SA', developer: true },
    { name: 'Atari Interactive (formerly Hasbro Interactive)', developer: true },
    { name: 'Atlus', developer: true },
    { name: 'Atomic Planet Entertainment', developer: true },
    { name: 'Attic Entertainment Software', developer: true },
    { name: 'Avalanche Software', developer: true },
    { name: 'Avalanche Studios', developer: true },
    { name: 'Aventurine SA', developer: true },
    { name: 'Babaroga', developer: true },
    { name: 'Backbone Entertainment', developer: true },
    { name: 'Bandai Namco Studios', developer: true },
    { name: 'Banpresto', developer: true },
    { name: 'Bauhaus Entertainment', developer: true },
    { name: 'Beenox', developer: true },
    { name: 'Behaviour Interactive', developer: true },
    { name: 'Behaviour Santiago', developer: true },
    { name: 'Bethesda Game Studios', developer: true },
    { name: 'Big Finish Games', developer: true },
    { name: 'Big Huge Games', developer: true },
    { name: 'BioWare', developer: true },
    { name: 'The Bitmap Brothers', developer: true },
    { name: 'Bits Studios', developer: true },
    { name: 'Bizarre Creations', developer: true },
    { name: 'Black Forest Games', developer: true },
    { name: 'Black Isle Studios', developer: true },
    { name: 'Black Rock Studio', developer: true },
    { name: 'Black Wing Foundation', developer: true },
    { name: 'Blitz Games Studios', developer: true },
    { name: 'Blizzard Entertainment', developer: true },
    { name: 'Blueside', developer: true },
    { name: 'Blue Byte', developer: true },
    { name: 'Blue Fang Games', developer: true },
    { name: 'Blue Tongue Entertainment', developer: true },
    { name: 'Bluehole', developer: true },
    { name: 'Bohemia Interactive', developer: true },
    { name: 'Boss Fight Entertainment', developer: true },
    { name: 'Boss Key Productions', developer: true },
    { name: 'BreakAway Games', developer: true },
    { name: 'Brøderbund', developer: true },
    { name: 'Bugbear Entertainment', developer: true },
    { name: 'Buka Entertainment', developer: true },
    { name: 'Bullfrog Productions', developer: true },
    { name: 'Bungie', developer: true },
    { name: 'Capcom', developer: true },
    { name: 'Capcom Vancouver', developer: true },
    { name: 'Carbine Studios', developer: true },
    { name: 'Cauldron', developer: true },
    { name: 'Cave', developer: true },
    { name: 'Cavia', developer: true },
    { name: 'CCP Games', developer: true },
    { name: 'CD Projekt Red', developer: true },
    { name: 'Certain Affinity', developer: true },
    { name: 'Chair Entertainment', developer: true },
    { name: 'Chunsoft', developer: true },
    { name: 'Cing', developer: true },
    { name: 'Clap Hanz', developer: true },
    { name: 'Climax Entertainment', developer: true },
    { name: 'Climax Studios', developer: true },
    { name: 'Cloud Imperium Games', developer: true },
    { name: 'Clover Studio', developer: true },
    { name: 'Coded Illusions', developer: true },
    { name: 'Codemasters', developer: true },
    { name: 'Coktel Vision', developer: true },
    { name: 'Colossal Order', developer: true },
    { name: 'Compile Heart', developer: true },
    { name: 'Compulsion Games', developer: true },
    { name: 'Core Design', developer: true },
    { name: 'Crafts & Meister', developer: true },
    { name: 'Creat Studios', developer: true },
    { name: 'Creative Assembly', developer: true },
    { name: 'Criterion Games', developer: true },
    { name: 'Croteam', developer: true },
    { name: 'Cryo Interactive', developer: true },
    { name: 'Cryptic Studios', developer: true },
    { name: 'Crystal Dynamics', developer: true },
    { name: 'Crytek', developer: true },
    { name: 'Crytek UK', developer: true },
    { name: 'Cyan Worlds', developer: true },
    { name: 'Cyanide', developer: true },
    { name: 'Cyberdreams', developer: true },
    { name: 'CyberConnect2', developer: true },
    { name: 'Cyberlore Studios', developer: true },
    { name: 'CyberStep', developer: true },
    { name: 'Cygames', developer: true },
    { name: 'Dambuster Studios', developer: true },
    { name: 'Day 1 Studios', developer: true },
    { name: 'Deadline Games', developer: true },
    { name: 'Deck13', developer: true },
    { name: 'Demiurge Studios', developer: true },
    { name: 'devCAT Studios', developer: true },
    { name: 'Dhruva Interactive', developer: true },
    { name: 'Die Gute Fabrik', developer: true },
    { name: 'Digital Extremes', developer: true },
    { name: 'Digital Illusions CE (EA DICE)', developer: true },
    { name: 'DICE Los Angeles', developer: true },
    { name: 'Digital Reality', developer: true },
    { name: 'Dimps', developer: true },
    { name: 'Disney Interactive Studios', developer: true },
    { name: 'Dontnod Entertainment', developer: true },
    { name: 'Double Fine Productions', developer: true },
    { name: 'Double Helix Games', developer: true },
    { name: 'Dynamix', developer: true },
    { name: 'Dovetail Games', developer: true },
    { name: 'Egosoft', developer: true },
    { name: 'Electronic Arts', developer: true },
    { name: 'Elemental Games', developer: true },
    { name: 'Engine Software', developer: true },
    { name: 'Ensemble Studios', developer: true },
    { name: 'Epic Games', developer: true },
    { name: 'Epicenter Studios', developer: true },
    { name: 'Epyx', developer: true },
    { name: 'Etranges Libellules', developer: true },
    { name: 'Eugen Systems', developer: true },
    { name: 'Eurocom', developer: true },
    { name: 'Evolution Studios', developer: true },
    { name: 'Eyedentity Games', developer: true },
    { name: 'F4', developer: true },
    { name: 'Facepunch Studios', developer: true },
    { name: 'FarSight Studios', developer: true },
    { name: 'Fatshark', developer: true },
    { name: 'feelplus', developer: true },
    { name: 'Firaxis Games', developer: true },
    { name: 'Firefly Studios', developer: true },
    { name: 'Firesprite', developer: true },
    { name: 'First Star Software', developer: true },
    { name: 'Flagship Studios', developer: true },
    { name: 'Flying Wild Hog', developer: true },
    { name: 'Foundation 9 Entertainment', developer: true },
    { name: 'Fox Interactive', developer: true },
    { name: 'Fox Digital Entertainment', developer: true },
    { name: 'FoxNext', developer: true },
    { name: 'Frictional Games', developer: true },
    { name: 'Frogwares', developer: true },
    { name: 'FromSoftware', developer: true },
    { name: 'Frontier Developments', developer: true },
    { name: 'Frozenbyte', developer: true },
    { name: 'FUN Labs', developer: true },
    { name: 'Funcom', developer: true },
    { name: 'Futuremark', developer: true },
    { name: 'Gaijin Entertainment', developer: true },
    { name: 'Game Arts', developer: true },
    { name: 'Game Freak', developer: true },
    { name: 'GameHouse', developer: true },
    { name: 'Gameloft', developer: true },
    { name: 'Gearbox Software', developer: true },
    { name: 'Geewa', developer: true },
    { name: 'Genki', developer: true },
    { name: 'Glu Mobile', developer: true },
    { name: 'Gogii Games', developer: true },
    { name: 'Good-Feel', developer: true },
    { name: 'Granzella', developer: true },
    { name: 'Grasshopper Manufacture', developer: true },
    { name: 'Gravity', developer: true },
    { name: 'Gremlin Interactive', developer: true },
    { name: 'Grezzo', developer: true },
    { name: 'Griptonite Games', developer: true },
    { name: 'GSC Game World', developer: true },
    { name: 'Guerrilla Cambridge', developer: true },
    { name: 'Guerrilla Games', developer: true },
    { name: 'GungHo Online Entertainment', developer: true },
    { name: 'Gust Corporation', developer: true },
    { name: 'Haemimont Games', developer: true },
    { name: 'HAL Laboratory', developer: true },
    { name: 'Halfbrick', developer: true },
    { name: 'Hanaho', developer: true },
    { name: 'Hangar 13', developer: true },
    { name: 'Harebrained Schemes', developer: true },
    { name: 'Harmonix Music Systems', developer: true },
    { name: 'HB Studios', developer: true },
    { name: 'HeroCraft', developer: true },
    { name: 'High Moon Studios', developer: true },
    { name: 'High Voltage Software', developer: true },
    { name: 'Hoplon Infotainment', developer: true },
    { name: 'Hothead Games', developer: true },
    { name: 'Housemarque', developer: true },
    { name: 'Hudson Soft', developer: true },
    { name: 'Human Head Studios', developer: true },
    { name: 'Humongous Entertainment', developer: true },
    { name: 'Hyperion Entertainment', developer: true },
    { name: 'id Software', developer: true },
    { name: 'Idea Factory', developer: true },
    { name: 'Idol Minds', developer: true },
    { name: 'Imageepoch', developer: true },
    { name: 'Image & Form', developer: true },
    { name: 'Infinity Ward', developer: true },
    { name: 'Infocom', developer: true },
    { name: 'Incredible Technologies', developer: true },
    { name: 'indieszero', developer: true },
    { name: 'Innerloop Studios', developer: true },
    { name: 'Insomniac Games', developer: true },
    { name: 'Intelligent Systems', developer: true },
    { name: 'Interplay Entertainment', developer: true },
    { name: 'Introversion Software', developer: true },
    { name: 'inXile Entertainment', developer: true },
    { name: 'IO Interactive', developer: true },
    { name: 'Ion Storm', developer: true },
    { name: 'Ion Storm Austin', developer: true },
    { name: 'Irem', developer: true },
    { name: 'Iron Galaxy Studios', developer: true },
    { name: 'Irrational Games', developer: true },
    { name: 'Ivory Tower', developer: true },
    { name: 'Jadestone Group', developer: true },
    { name: 'Jagex', developer: true },
    { name: 'Jaleco', developer: true },
    { name: 'Jam City', developer: true },
    { name: 'Javaground', developer: true },
    { name: 'JoWood Entertainment AG', developer: true },
    { name: 'Juice Games', developer: true },
    { name: 'Jupiter', developer: true },
    { name: 'JV Games', developer: true },
    { name: 'Kairosoft', developer: true },
    { name: 'Kalypso Media', developer: true },
    { name: 'Kaos Studios', developer: true },
    { name: 'Keen Software House', developer: true },
    { name: 'Kiloo Games', developer: true },
    { name: 'King', developer: true },
    { name: 'Koei', developer: true },
    { name: 'KOG Studios', developer: true },
    { name: 'Kojima Productions', developer: true },
    { name: 'Konami', developer: true },
    { name: 'Kongzhong', developer: true },
    { name: 'Krome Studios', developer: true },
    { name: 'Krome Studios Melbourne', developer: true },
    { name: 'Kuju Entertainment', developer: true },
    { name: 'Kunos Simulazioni', developer: true },
    { name: 'Kush Games', developer: true },
    { name: 'Kuma Reality Games', developer: true },
    { name: 'Kylotonn', developer: true },
    { name: 'Larian Studios', developer: true },
    { name: 'Legacy Interactive', developer: true },
    { name: 'Legend Entertainment', developer: true },
    { name: 'Legendo Entertainment', developer: true },
    { name: 'LEGO Group', developer: true },
    { name: 'Level-5', developer: true },
    { name: 'Lionhead Studios', developer: true },
    { name: 'Liquid Entertainment', developer: true },
    { name: 'Little Green Men Games', developer: true },
    { name: 'LK Avalon', developer: true },
    { name: 'Llamasoft', developer: true },
    { name: 'Linden Lab', developer: true },
    { name: 'Looking Glass Studios', developer: true },
    { name: 'LucasArts', developer: true },
    { name: 'Luma Arcade', developer: true },
    { name: 'Luxoflux', developer: true },
    { name: 'MachineGames', developer: true },
    { name: 'Magenta Software', developer: true },
    { name: 'MAGES.', developer: true },
    { name: 'Majesco Entertainment', developer: true },
    { name: 'Marvelous Entertainment', developer: true },
    { name: 'Massive Entertainment', developer: true },
    { name: 'Masthead Studios', developer: true },
    { name: 'Maxis Software', developer: true },
    { name: 'Mean Hamster Software', developer: true },
    { name: 'Media Molecule', developer: true },
    { name: 'Mediatonic', developer: true },
    { name: 'MegaZebra', developer: true },
    { name: 'Mercury Steam', developer: true },
    { name: 'Metropolis Software', developer: true },
    { name: 'MicroProse Software', developer: true },
    { name: 'Microsoft Studios', developer: true },
    { name: 'Midway Games', developer: true },
    { name: 'Milestone', developer: true },
    { name: 'Milestone S.r.l.', developer: true },
    { name: 'Mistwalker', developer: true },
    { name: 'Mitchell Corporation', developer: true },
    { name: 'MLB Advanced Media', developer: true },
    { name: 'Mojang AB', developer: true },
    { name: 'Monolith Productions', developer: true },
    { name: 'Monolith Soft', developer: true },
    { name: 'Mythic Entertainment', developer: true },
    { name: 'Nadeo', developer: true },
    { name: 'Nanobit', developer: true },
    { name: 'Natsume', developer: true },
    { name: 'Naughty Dog', developer: true },
    { name: 'NCsoft', developer: true },
    { name: 'NDOORS Corporation', developer: true },
    { name: 'Neowiz', developer: true },
    { name: 'Nerve Software', developer: true },
    { name: 'NetDevil', developer: true },
    { name: 'Netdragon', developer: true },
    { name: 'Netease', developer: true },
    { name: 'NetherRealm Studios', developer: true },
    { name: 'Neversoft', developer: true },
    { name: 'Nevosoft', developer: true },
    { name: 'NexonNexon Korea', developer: true },
    { name: 'Next Level Games', developer: true },
    { name: 'NGD Studios', developer: true },
    { name: 'Niantic', developer: true },
    { name: 'Nibris', developer: true },
    { name: 'Nihon Falcom', developer: true },
    { name: 'Nikita Online', developer: true },
    { name: 'Ninjabee', developer: true },
    { name: 'Ninja Theory', developer: true },
    { name: 'Nintendo', developer: true },
    { name: 'Nippon Ichi Software', developer: true },
    { name: 'Nival', developer: true },
    { name: 'Nordeus', developer: true },
    { name: 'NovaLogic', developer: true },
    { name: 'Novarama', developer: true },
    { name: 'n-Space', developer: true },
    { name: 'Obsidian Entertainment', developer: true },
    { name: 'Oddworld Inhabitants', developer: true },
    { name: 'Omega Force', developer: true },
    { name: 'Origin Systems', developer: true },
    { name: 'Outrage Entertainment', developer: true },
    { name: 'Overkill Software', developer: true },
    { name: 'Oxygen Studios', developer: true },
    { name: 'Page 44 Studios', developer: true },
    { name: 'Pangea Software', developer: true },
    { name: 'People Can Fly', developer: true },
    { name: 'Project Sora', developer: true },
    { name: 'Papaya Studio', developer: true },
    { name: 'Project Soul', developer: true },
    { name: 'Panther Games Pty Ltd', developer: true },
    { name: 'Paradox Development Studio', developer: true },
    { name: 'Parallax Software', developer: true },
    { name: 'Pandemic Studios', developer: true },
    { name: 'Pendulab Private', developer: true },
    { name: 'Pendulo Studios', developer: true },
    { name: 'Penguin Software', developer: true },
    { name: 'Perfect World', developer: true },
    { name: 'Petroglyph', developer: true },
    { name: 'Phantagram', developer: true },
    { name: 'Phenomic Game Development', developer: true },
    { name: 'Pipeworks Studios', developer: true },
    { name: 'Piranha Bytes', developer: true },
    { name: 'Pi Studios', developer: true },
    { name: 'Pivotal Games', developer: true },
    { name: 'Pixel Press', developer: true },
    { name: 'Playdom', developer: true },
    { name: 'Playfish', developer: true },
    { name: 'PlayFirst', developer: true },
    { name: 'Playground Games', developer: true },
    { name: 'PlatinumGames', developer: true },
    { name: 'Polyphony Digital', developer: true },
    { name: 'PopCap Games', developer: true },
    { name: 'Press Play', developer: true },
    { name: 'Psyonix', developer: true },
    { name: 'Punch Entertainment', developer: true },
    { name: 'Pyro Mobile', developer: true },
    { name: 'Q Entertainment', developer: true },
    { name: 'Q-Games', developer: true },
    { name: 'Quantic Dream', developer: true },
    { name: 'Radical Entertainment', developer: true },
    { name: 'Rage Games', developer: true },
    { name: 'Rainbow Studios', developer: true },
    { name: 'Rare', developer: true },
    { name: 'Raven Software', developer: true },
    { name: 'Ready at Dawn', developer: true },
    { name: 'Red Entertainment', developer: true },
    { name: 'Reality Pump Studios', developer: true },
    { name: 'Realtime Associates', developer: true },
    { name: 'Realtime Worlds', developer: true },
    { name: 'Rebellion Developments', developer: true },
    { name: 'RedLynx', developer: true },
    { name: 'Red Thread Games', developer: true },
    { name: 'Red Storm Entertainment', developer: true },
    { name: 'RedTribe (Tribalant)', developer: true },
    { name: 'Reflections Interactive', developer: true },
    { name: 'Reflexive Entertainment', developer: true },
    { name: 'Relic Entertainment', developer: true },
    { name: 'Remedy Entertainment', developer: true },
    { name: 'Respawn Entertainment', developer: true },
    { name: 'Reto-Moto', developer: true },
    { name: 'Retro Studios', developer: true },
    { name: 'Revolution Software', developer: true },
    { name: 'Riot Games', developer: true },
    { name: 'Rising Star Games', developer: true },
    { name: 'Robot Entertainment', developer: true },
    { name: 'Rockstar GamesRockstar IndiaRockstar LeedsRockstar LincolnRockstar LondonRockstar New EnglandRockstar NorthRockstar San DiegoRockstar Toronto', developer: true },
    { name: 'Rocksteady Studios', developer: true },
    { name: 'Robinson Technologies', developer: true },
    { name: 'Rovio Entertainment', developer: true },
    { name: 'Ruffian Games', developer: true },
    { name: 'Runic Games', developer: true },
    { name: 'Running With Scissors', developer: true },
    { name: 'Sand Grain Studios', developer: true },
    { name: 'Schell Games', developer: true },
    { name: 'SCS Software', developer: true },
    { name: 'Sega', developer: true },
    { name: 'Sensible Software', developer: true },
    { name: 'Serious Games Interactive', developer: true },
    { name: 'Sega AM2', developer: true },
    { name: 'SIE Bend Studio', developer: true },
    { name: 'SIE Foster City Studio', developer: true },
    { name: 'SIE Japan Studio', developer: true },
    { name: 'SIE London Studio', developer: true },
    { name: 'SIE San Diego Studio', developer: true },
    { name: 'SIE Santa Monica Studio', developer: true },
    { name: 'SCE Studio Liverpool', developer: true },
    { name: 'SIE Worldwide Studios', developer: true },
    { name: 'Shanda', developer: true },
    { name: 'Sherman3D', developer: true },
    { name: 'Sierra Entertainment', developer: true },
    { name: 'Silicon Knights', developer: true },
    { name: 'Silicon Studio', developer: true },
    { name: 'Simtex', developer: true },
    { name: 'Sledgehammer Games', developer: true },
    { name: 'Snail Games', developer: true },
    { name: 'Slightly Mad Studios', developer: true },
    { name: 'Slipgate Studios', developer: true },
    { name: 'Smilegate', developer: true },
    { name: 'SNK', developer: true },
    { name: 'Sobee Studios', developer: true },
    { name: 'Snowblind Studios', developer: true },
    { name: 'Software 2000', developer: true },
    { name: 'Sonic Team', developer: true },
    { name: 'Sony Interactive Entertainment', developer: true },
    { name: 'Sora Ltd.', developer: true },
    { name: 'Spectrum HoloByte', developer: true },
    { name: 'Spellbound Entertainment', developer: true },
    { name: 'Spike', developer: true },
    { name: 'Spike Chunsoft', developer: true },
    { name: 'Spil Games', developer: true },
    { name: 'Splash Damage', developer: true },
    { name: 'Sproing Interactive Media', developer: true },
    { name: 'Square Enix', developer: true },
    { name: 'Stainless Games', developer: true },
    { name: 'Stainless Steel Studios', developer: true },
    { name: 'Starbreeze Studios', developer: true },
    { name: 'Stardock', developer: true },
    { name: 'Sting Entertainment', developer: true },
    { name: 'Strategic Simulations', developer: true },
    { name: 'Stoic Studio', developer: true },
    { name: 'Strawdog Studios', developer: true },
    { name: 'Straylight Studios', developer: true },
    { name: 'Streamline Studios', developer: true },
    { name: 'Success', developer: true },
    { name: 'Sucker Punch Productions', developer: true },
    { name: 'Sumo Digital', developer: true },
    { name: 'Sunflowers Interactive Entertainment Software', developer: true },
    { name: 'Supercell', developer: true },
    { name: 'Supermassive Games', developer: true },
    { name: 'SuperVillain Studios', developer: true },
    { name: 'Survios', developer: true },
    { name: 'Swingin\' Ape Studios', developer: true },
    { name: 'StormRegion', developer: true },
    { name: 'Syn Sophia', developer: true },
    { name: 'Taito', developer: true },
    { name: 'Tango Gameworks', developer: true },
    { name: 'Tag Games', developer: true },
    { name: 'TaleWorlds', developer: true },
    { name: 'Tamsoft', developer: true },
    { name: 'Tantrumedia', developer: true },
    { name: 'Tantalus Media', developer: true },
    { name: 'Tarsier Studios', developer: true },
    { name: 'Tate Interactive', developer: true },
    { name: 'Team17', developer: true },
    { name: 'Team Bondi', developer: true },
    { name: 'Team Ico', developer: true },
    { name: 'Team Ninja', developer: true },
    { name: 'Techland', developer: true },
    { name: 'Telltale Games', developer: true },
    { name: 'Tencent', developer: true },
    { name: 'Tencent Games', developer: true },
    { name: 'Tequila Works', developer: true },
    { name: 'Terminal Reality', developer: true },
    { name: 'Teyon', developer: true },
    { name: 'The9', developer: true },
    { name: 'The Chinese Room', developer: true },
    { name: 'THQ', developer: true },
    { name: 'THQ Nordic', developer: true },
    { name: 'Three Fields Entertainment', developer: true },
    { name: 'Three Rings Design', developer: true },
    { name: 'TimeGate Studios', developer: true },
    { name: 'Toaplan', developer: true },
    { name: 'ToeJam & Earl Productions', developer: true },
    { name: 'TopWare Interactive', developer: true },
    { name: 'Torpex Games', developer: true },
    { name: 'Torus Games', developer: true },
    { name: 'Tose', developer: true },
    { name: 'Toys for Bob', developer: true },
    { name: 'Trapdoor', developer: true },
    { name: 'Transmission Games', developer: true },
    { name: 'Traveller\'s Tales', developer: true },
    { name: 'Treyarch', developer: true },
    { name: 'Treasure', developer: true },
    { name: 'tri-Ace', developer: true },
    { name: 'Tripwire Interactive', developer: true },
    { name: 'Triumph Studios', developer: true },
    { name: 'Turn 10 Studios', developer: true },
    { name: 'Turtle Rock Studios', developer: true },
    { name: 'Two Tribes', developer: true },
    { name: 'Typhoon Games', developer: true },
    { name: 'Ubisoft', developer: true },
    { name: 'Ultimate Play the Game', developer: true },
    { name: 'Unique Development Studios', developer: true },
    { name: 'United Front Games', developer: true },
    { name: 'Universomo', developer: true },
    { name: 'Valve Corporation', developer: true },
    { name: 'Vanillaware', developer: true },
    { name: 'Venan Entertainment', developer: true },
    { name: 'Vicarious Visions', developer: true },
    { name: 'Vigil Games', developer: true },
    { name: 'Virtual Heroes, Inc.', developer: true },
    { name: 'Visceral Games', developer: true },
    { name: 'Visual Concepts', developer: true },
    { name: 'Volition', developer: true },
    { name: 'Vostok Games', developer: true },
    { name: 'VoxelStorm', developer: true },
    { name: 'Wahoo Studios', developer: true },
    { name: 'Warhorse Studios', developer: true },
    { name: 'Wargaming', developer: true },
    { name: 'Wargaming Saint Petersburg', developer: true },
    { name: 'Wargaming Seattle', developer: true },
    { name: 'WB Games', developer: true },
    { name: 'Webfoot Technologies', developer: true },
    { name: 'Westwood Studios', developer: true },
    { name: 'Westone Bit Entertainment', developer: true },
    { name: 'Wideload Games', developer: true },
    { name: 'Wildfire Studios', developer: true },
    { name: 'Wizet', developer: true },
    { name: 'Wolfire Games', developer: true },
    { name: 'World Forge', developer: true },
    { name: 'XPEC Entertainment', developer: true },
    { name: 'Yager Development', developer: true },
    { name: 'Yuke\'s', developer: true },
    { name: 'ZeniMax Online Studios', developer: true },
    { name: 'Zipper Interactive', developer: true },
    { name: 'Zombie Studios', developer: true },
    { name: 'ZootFly', developer: true },
    { name: 'Zylom', developer: true },
    { name: 'Zynga', developer: true }
  ])
  .then(newCompanies => Promise.all(newCompanies.map(company => Company.create(company))))
  .catch(err => console.log('err: ', err))